export const LOGIN_START_ACTION = "LOGIN_START_ACTION";
export const LOGIN_SUCCESS_ACTION = "LOGIN_SUCCESS_ACTION";
export const LOGIN_FAIL_ACTION = "LOGIN_FAIL_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const LOADING_ACTION = "LOADING_ACTION";
export const LOADING_PROCESS_ACTION = "LOADING_PROCESS_ACTION";
export const ERROR_ACTION = "ERROR_ACTION";
export const SET_PAGE_HEADER_ACTION = "SET_PAGE_HEADER_ACTION";
export const SET_PAGE_TITLE_ACTION = "SET_PAGE_TITLE_ACTION";


export const INIT_PAGE_ACTION = "INIT_PAGE_ACTION";
export const DYNAMIC_SUBMIT_ACTION = "DYNAMIC_SUBMIT_ACTION"
